### ISSUE TITLE
Add Latest 2020 Conf videos

### ISSUE THREAD

**Issue by Ishankhan21** [simonccarter/react-conf-videos#196]
Please add latest 2020 conf videos , at-least someone must add the 2020 section and add videos from a single conf, and then we can add more videos. 

https://dev.to/benghamine/full-list-of-react-conferences-in-2020-1a3o

**Comment by simonccarter** [comment]
@Ishankhan21 you are more than welcome to add these yourself. The instructions to do so are in the readme.md file.
